(function(){/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/ 
'use strict';var f=this||self;function g(a){return a};var h;function k(a,b){this.b=a===l&&b||"";this.a=m}var m={},l={};function n(a,b,d){a.addEventListener&&a.addEventListener(b,d,!1)};function p(a,b,d){if(Array.isArray(b))for(var c=0;c<b.length;c++)p(a,String(b[c]),d);else null!=b&&d.push(a+(""===b?"":"="+encodeURIComponent(String(b))))};function q(a,b,d=null){r(a,b,d)}function r(a,b,d){a.google_image_requests||(a.google_image_requests=[]);const c=a.document.createElement("img");if(d){const e=D=>{d&&d(D);c.removeEventListener&&c.removeEventListener("load",e,!1);c.removeEventListener&&c.removeEventListener("error",e,!1)};n(c,"load",e);n(c,"error",e)}c.src=b;a.google_image_requests.push(c)};var t=(a=null)=>a&&22==a.getAttribute("data-jc")?a:document.querySelector('[data-jc="22"]');var u=document,v=window;var w,x=new k(l,"//fonts.googleapis.com/css");w=x instanceof k&&x.constructor===k&&x.a===m?x.b:"type_error:Const";var y;if(void 0===h){var z=null,A=f.trustedTypes;if(A&&A.createPolicy){try{z=A.createPolicy("goog#html",{createHTML:g,createScript:g,createScriptURL:g})}catch(a){f.console&&f.console.error(a.message)}h=z}else h=z}(y=h)&&y.createScriptURL(w);function B(a){n(u,a.f,()=>{if(u[a.a])a.b&&(a.b=!1,a.c=Date.now(),C(a,0));else{if(-1!=a.c){const b=Date.now()-a.c;0<b&&(a.c=-1,C(a,1,b))}C(a,3)}})}function E(a){n(v,"click",b=>a.handleClick(b))} 
function C(a,b,d){var c={gqid:a.h,qqid:a.i};0==b&&(c["return"]=0);1==b&&(c["return"]=1,c.timeDelta=d);2==b&&(c.bgload=1);3==b&&(c.fg=1);b=[];for(var e in c)p(e,c[e],b);q(v,a.g+"&label=window_focus&"+b.join("&"),void 0);if(!(.01<Math.random())){a=(a=t(document.currentScript))&&a.getAttribute("data-jc-version")||"unknown";a=`https://${"pagead2.googleadservices.com"}/pagead/gen_204?id=jca&jc=${22}&version=${a}&sample=${.01}`;c=window;if(e=c.navigator)e=c.navigator.userAgent,e=/Chrome/.test(e)&&!/Edge/.test(e)? 
!0:!1;e&&c.navigator.sendBeacon?c.navigator.sendBeacon(a):q(c,a)}} 
class F{constructor(a,b,d){"undefined"!==typeof u.hidden?(this.a="hidden",this.f="visibilitychange"):"undefined"!==typeof u.mozHidden?(this.a="mozHidden",this.f="mozvisibilitychange"):"undefined"!==typeof u.msHidden?(this.a="msHidden",this.f="msvisibilitychange"):"undefined"!==typeof u.webkitHidden&&(this.a="webkitHidden",this.f="webkitvisibilitychange");this.g=a;this.b=!1;this.c=-1;this.h=b;this.i=d;u[this.a]&&C(this,2);B(this);E(this)}handleClick(){this.b=!0;v.setTimeout(()=>{this.b=!1},5E3)}};{const a=t(document.currentScript);if(null==a)throw Error("JSC not found 22");var G;{const b={},d=a.attributes;for(let c=d.length-1;0<=c;c--){const e=d[c].name;0===e.indexOf("data-jcp-")&&(b[e.substring(9)]=d[c].value)}G=b}window.window_focus_for_click=new F(G.url,G["gws-id"],G["qem-id"])};}).call(this);
